site_name: Angular Geocoder Autocomplete
site_url: https://geoapify.github.io/angular-geocoder-autocomplete/

theme:
  name: material
  logo: assets/geoapify-white-logo-only.png
  favicon: assets/favicon.ico
  features:
    - content.code.copy
    - navigation.expand

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - API Reference: api-reference.md
  - Examples: examples.md
  - Standalone Usage: standalone-usage.md

repo_url: https://github.com/geoapify/angular-geocoder-autocomplete
repo_name: GitHub

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geoapify
